site_name: ChimeraFX
repo_url: https://github.com/effelle/ChimeraFX
site_url: https://effelle.github.io/ChimeraFX/
repo_name: ChimeraFX
edit_uri: "" 

theme:
  name: material
  logo: assets/ChimeraFX_rgb_vector.png
  favicon: assets/ChimeraFX_rgb_logo.png
  features:
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - search.suggest
    - content.code.copy
  palette:
    # Light Mode
    # - scheme: default
    #   primary: custom
    #   # primary: blue grey
    #   accent: purple
      # toggle:
      #   icon: material/brightness-7
      #   name: Switch to dark mode
    # Dark Mode
    - scheme: slate
      primary: custom
      accent: purple
      # toggle:
      #   icon: material/brightness-4
      #   name: Switch to light mode

extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - Guide:
    - Installation: Installation.md
    - Controls: Controls.md
    - Effect Presets: Effect-Presets.md
    - Troubleshooting: Troubleshooting.md
    - Effect Library: Effects-Library.md
    - The Story: The-Story.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true